// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddDriverTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addDriver() {
    driver.get("http://localhost:3000/dashboard-login");
    driver.manage().window().setSize(new Dimension(1401, 753));
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("admin");
    driver.findElement(By.name("password")).sendKeys("admin123");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".col-4:nth-child(1) .image")).click();
    driver.findElement(By.cssSelector(".box-part:nth-child(1)")).click();
    driver.findElement(By.name("vehicletype")).click();
    driver.findElement(By.name("vehicletype")).sendKeys("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGNXPEC_dObFKRj-sHN-Xi7wS2F7Ou0u4EoG-Ua_zAzamm7mgkJPQLTM8mF8JswL5ZSP8&usqp=CAU");
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("shamod");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("shamod@gmail.com");
    driver.findElement(By.name("phone")).click();
    driver.findElement(By.name("phone")).sendKeys("0754465234");
    driver.findElement(By.name("vehiclename")).sendKeys("Alto-ECD-2367");
    driver.findElement(By.name("branch")).click();
    driver.findElement(By.name("branch")).sendKeys("gampaha");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("shamod123");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
  }
}
